// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOpDC8rIAa56bL9FfLIBzEfi-hPMDQ3Qk',
    appId: '1:176656721543:web:c6a774b8975de3b36ffa22',
    messagingSenderId: '176656721543',
    projectId: 'ilm-online',
    authDomain: 'ilm-online.firebaseapp.com',
    storageBucket: 'ilm-online.appspot.com',
    measurementId: 'G-1913ETHG81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpDC8rIAa56bL9FfLIBzEfi-hPMDQ3Qk',
    appId: '1:176656721543:android:c4e3b2383dec77cb6ffa22',
    messagingSenderId: '176656721543',
    projectId: 'ilm-online',
    storageBucket: 'ilm-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOpDC8rIAa56bL9FfLIBzEfi-hPMDQ3Qk',
    appId: '1:176656721543:ios:897cdad9219d067a6ffa22',
    messagingSenderId: '176656721543',
    projectId: 'ilm-online',
    storageBucket: 'ilm-online.appspot.com',
    iosClientId:
        '176656721543-5t6a8fj2t3hf0c50v780avkgnis0vrbs.apps.googleusercontent.com',
    iosBundleId: 'com.citizenraf.ilmOnlineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOpDC8rIAa56bL9FfLIBzEfi-hPMDQ3Qk',
    appId: '1:176656721543:ios:1b0bb6f1832187556ffa22',
    messagingSenderId: '176656721543',
    projectId: 'ilm-online',
    storageBucket: 'ilm-online.appspot.com',
    iosClientId:
        '176656721543-aqpgps7asb0d3gkt7fnu3o7196a9c73j.apps.googleusercontent.com',
    iosBundleId: 'com.example.ilmOnlineApp',
  );
}
